### ISSUE TITLE
[Bug] Suppressing modal popups in Temporal UI no longer works with single binary

### ISSUE THREAD

**Issue by MasonEgger** [temporalio/cli#234]
### What are you really trying to do?
I am trying to suppress modal popups when launching the Temporal UI. 

### Describe the bug
When using the Docker Compose method of serving the Temporal UI I was able to suppress modal popups with the following environment variable

`export TEMPORAL_NOTIFY_ON_NEW_VERSION=false`

This no longer is the case

![image (2)](https://github.com/temporalio/cli/assets/11214847/28eda575-f700-4973-b07c-37d50ffff37c)

**Comment by cretz** [comment]
:+1: Need `NotifyOnNewVersion: false` at https://github.com/temporalio/cli/blob/075fc0d99902d841770103501319740be2cafd0d/server/commands.go#L231

**Comment by feedmeapples** [comment]
this could be controlled by the `--config` flag when we add it back. Users can point it to a yaml config file that has the `notifyOnNewVersion` entry, similar to this https://github.com/temporalio/ui/blob/25f46991c6d38ebeae416d0a45cf4b128db55789/server/config/development.yaml#L13

lmk what you think

**Comment by cretz** [comment]
We should turn this off by default I think

**Comment by feedmeapples** [comment]
as of now we do plan to show notification for new Temporal CLI versions. Then yes the UI and Server notifications should be disabled

For other UI tooltips i think these should stay? And likely controlled by a different environment variable than `TEMPORAL_NOTIFY_ON_NEW_VERSION` cc @canvanooo @Alex-Tideman wdyt?

**Comment by tomwheeler** [comment]
I have a very strong preference for having some way of suppressing any notification banner or popup of any kind. 

These are a huge distraction in a training environment (e.g., in an "Intro to Temporal" workshop) and are also not helpful since the people seeing them likely don't have the ability to upgrade the environment anyway (i.e., because it's something we configure and deploy for them). To be clear, we do try our best to stay current, but we also re-test all demos and exercises before deploying a new version. It makes our training look outdated when a "new version" banner shows up the morning of a workshop. The "Check out this new feature" popups aren't meaningful when we're teaching people who are new to Temporal, since _everything_ is new to them.

It does not matter much to me if suppressing all banners and popups requires setting one environment variables or two, so long as they are documented.

**Comment by lorensr** [comment]
> as of now we do plan to show notification for new Temporal CLI versions.

this notification will be on the command line, not in the UI, right?

**Comment by josh-berry** [comment]
I'm not quite sure I understand why this is a CLI issue? The CLI doesn't use docker-compose at all to start the server (/frontend), and when I tested `temporal server start-dev` with older versions just now it never showed me this notification. It's quite possible I'm missing something, though.

@MasonEgger @tomwheeler Can one of you share (a link to) the exact set of steps you're using to start the server (/ui-server)?

I do see the environment variable mentioned in the issue description, but it's in [ui-server](https://github.com/temporalio/ui-server), not in the CLI, so I'm wondering if there's something weird about how you're starting the server, or maybe something that changed in whatever `docker-compose.yaml` you're using, that's causing the notification to still appear.

**Comment by tomwheeler** [comment]
@josh-berry The vast majority of our learners use GitPod (via a configuration that we provide) to launch a Temporal development environment that's accessible through their browser. That environment includes the Temporal Web UI, which they use during hands-on exercises. 

For the courses we developed (or started developing) last year, such as _Temporal 101 with Go_ and _Temporal 101 with TypeScript_, the environment was created within GitPod through Docker Compose ([example](https://github.com/temporalio/edu-101-go-code/blob/main/.gitpod.yml#L32), for reference). The Docker Compose configuration we created for this set the env var necessary to suppress the distracting popup ([example](https://github.com/temporalio/edu-101-go-code/blob/main/temporal-server/docker-compose.yml#L72)).

In our more recent courses, such as _Temporal 101 with Java_, we have shifted from using Docker Compose to using the `temporal` CLI to start the Temporal cluster and Web UI ([example](https://github.com/temporalio/edu-101-java-code/blob/main/.gitpod.yml#L13)). Unfortunately, the unwanted notifications are displayed when launching via `temporal` instead of through Docker Compose. These notifications are not only distracting to someone in a 101 training course, they are also meaningless because the learner doesn't have the ability to modify the configuration for that GitPod environment.  

The screenshot that Mason included seems to be one advertising new features in the Web UI, although we originally began setting the environment variable to suppress notifications about new versions (since we need to test all the exercises again before upgrading to ensure everything works OK). However, our goal is to suppress all of these one-time notifications, regardless of whether the environment is configured with GitPod or the `temporal` CLI. Once we're able to do that, then we will migrate the older courses away from Docker Compose and `tctl` to the `temporal` command.

**Comment by tomwheeler** [comment]
I should add that Mason was the one who did the migration from Docker Compose to `temporal` and I didn't study the implementation that closely until now. It occurs to me that he's not setting the environment variable that was getting set with Docker Compose, and perhaps if that was being set, this popup would be suppressed. 

OTOH, Ruslan knows more about how the CLI and UI work than me and his comments indicate that some CLI options needed to be added in order to suppress the unwanted notifications.

**Comment by Alex-Tideman** [comment]
Wanted to chime in here. The popup notification was removed in this commit: https://github.com/temporalio/ui/pull/1460

That was released in ui-server version `2.17.0`. The current ui-server version on the latest CLI is `2.17.2`.

The temporal CLI gets an automatic PR from dependabot when a new ui-server release is created. This is our latest version PR (`2.18.0`): https://github.com/temporalio/cli/pull/315

**Comment by Alex-Tideman** [comment]
The TEMPORAL_NOTIFY_ON_NEW_VERSION env var didn't affect the popup notification. That env var is for the banner at the top when there is a new UI version.

**Comment by tomwheeler** [comment]
Thanks, @Alex-Tideman. Based on what you know, would you then think that if the `TEMPORAL_NOTIFY_ON_NEW_VERSION` env var was set within the process where the CLI was used to start the Web UI, then there would be no popup of any kind (because the one from the original screenshot is no longer used and because the new version notification would be suppressed)?

**Comment by Alex-Tideman** [comment]
Correct if TEMPORAL_NOTIFY_ON_NEW_VERSION is set to false. And if set to true, new version notification would not be a popup, it is a banner like the below screenshot.

<img width="1728" alt="Screen Shot 2023-08-28 at 9 58 07 AM" src="https://github.com/temporalio/cli/assets/7967403/e75515e4-ec8c-4a1f-96ce-df1d1056e587">

**Comment by cretz** [comment]
After internal discussions, this modal no longer appears in the latest release Temporal CLI (and embedded UI server), and we will not reintroduce anything else like it without ample thought into suppression and/or reuse of that env var.
