### ISSUE TITLE
[Bug] No `--fields` option for `temporal workflow list`

### ISSUE THREAD

**Issue by nathanielobrown** [temporalio/cli#705]
### What are you really trying to do?
Trying to list workflows customizing displayed fields, specifically showing the `HistorySizeBytes` field

### Describe the bug
I’m using Temporal CLI 1.1.1 (the latest version) on MacOS (I also got the same on Linux)  and when I try to use the `--fields` option for temporal workflow list as documented [here](https://docs.temporal.io/cli/workflow#list), it appears it is not a valid option and I get the following output. What’s going on? On an older version of the CLI (0.11.0) this option works fine

### Minimal Reproduction
1. Run `temporal workflow list --fields 'Type.Name,HistorySizeBytes'`
2. Output will be: `Error: unknown flag: --fields`  and then the command help which does not mention `--fields`

### Environment/Versions
- OS and processor: M1 Mac as well as Linux Intel
- Temporal Version: CLI 1.1.1
- MacOS installed via brew, Linux downloaded binary

**Comment by josh-berry** [comment]
Hi @nathanielobrown, unfortunately, this is intentional—the `--fields` option was removed in 0.12 as part of a major house-cleaning and rewrite we did across the entire CLI. 

We recommend people use `-o json` and use a tool like `jq` to parse the JSON output instead. The reason we went this route is the JSON output format is guaranteed to be stable, while the text output format (including field names and such) may change without notice. Also, maintaining `--fields` across a whole bunch of commands added a lot of complexity, and with JSON available, we didn't feel there was a strong enough reason to keep `--fields`.

That said, if there's a compelling reason why JSON won't work for you and you need the `--fields` option brought back, let us know, we're always willing to consider it!

As for the docs site still showing `--fields`, apologies for that—this is a known issue we're working on. We still have some internal tooling work to do to make sure the docs site is kept in sync with the latest CLI release. For now, the `--help` output is authoritative.

Hope this helps!

**Comment by nathanielobrown** [comment]
Ah, extracting the `history_size_bytes` field from JSON was the missing link for me! I guess I mistakenly assumed that only the fields specified would be included in the JSON option. Thank you for explaining

**Comment by josh-berry** [comment]
Sure thing! I'll go ahead and close this but don't hesitate to reach out again if you need anything else!
